<?php 

return [
    'choose_domain' => 'Domain auswählen...',
    'reg_new_domain' => 'Neue Domain registrieren',
    'use_own_domain' => 'Eigene Domain verwenden',
    'description' => 'Beschreibung',
    'balance_before_transaction' => 'Kontostand vor der Transaktion',
    'amount' => 'Betrag',
    'date' => 'Datum',
    'your_services' => 'Ihre Dienste',
    'results' => 'Ergebnisse',
    'more_info' => 'Weitere Informationen',
    'showing' => 'Zeige :count von :all Ergebnissen',
    'add_balance' => 'Guthaben hinzufügen',
    'order_new_service' => 'Neuen Dienst bestellen',
    'terminated' => 'Beendet',
    'cancelled' => 'Abgebrochen',
    'expand_collapse_row' => 'Zeile erweitern/zusammenklappen',
    'product' => 'Produkt',
    'service' => 'Dienst',
    'category' => 'Kategorie',
    'status' => 'Status',
    'details' => 'Details',
    'package' => 'Paket',
    'billing_cycle' => 'Abrechnungszyklus',
    'due_date' => 'Fälligkeitsdatum',
    'last_renewal_date' => 'Letztes Verlängerungsdatum',
    'next_invoice' => 'Nächste Rechnung',
    'no_orders_found' => 'Keine Bestellungen gefunden',
    'no_orders_found_desc' => 'Sie haben noch keine Bestellungen aufgegeben, neue Bestellungen werden hier sichtbar sein.',
    'paid' => 'Bezahlt',
    'unpaid' => 'Unbezahlt',
    'refunded' => 'Erstattet',
    'actions' => 'Aktionen',
    'no_records_found' => 'Keine Datensätze gefunden',
    'no_record_found_desc' => 'Sie haben noch keine :paid Rechnungen bezahlt, :paid Rechnungen werden hier angezeigt',
    'invoice' => 'Rechnung',
    'payment_not_received' => 'Zahlung noch nicht erhalten.',
    'checking_in' => 'Einchecken',
    'bitpave_payment_engine' => 'Betrieben von Bitpave Zahlungs-Engine',
    'payment_details' => 'Zahlungsdetails',
    'payment_total_is' => 'Ihr Gesamtbetrag beträgt :is für :for',
    'bitpave_instruction' => '1. Öffnen Sie Ihre Bitcoin-Wallet-App oder scannen Sie den QR-Code<br>
                    2. Senden Sie <u>exakt</u> <strong>:price</strong> BTC an
                    <strong>:wallet</strong><br>
                    3. Sie sind fertig 🚀 🙌',
    'wallet' => 'Wallet',
    'bitcoin_amount' => 'Bitcoin-Betrag',
    'awaiting_payment' => 'Zahlung wird erwartet...',
    'session_expired' => 'Sitzung abgelaufen',
    'copied' => 'Kopiert',
    'scanning_payments' => 'Zahlungen werden gescannt',
    'stripe_card_payment' => 'Zahlung mit Stripe-Karte',
    'credit_debit_card' => 'Kredit- oder Debitkarte',
    'submit_payment' => 'Zahlung senden',
    'provide_missing_information' => 'Fehlende Informationen angeben',
    'provide_missing_information_desc' => 'Wir sind verpflichtet, Informationen wie die Adresse zu erfassen. Bitte füllen Sie das folgende Formular aus, um fortzufahren.',
    'optional' => '(optional)',
    'organization' => 'Organisation',
    'company_name' => 'Firmenname',
    'select_an_option' => 'Eine Option auswählen',
    'address' => 'Adresse',
    'city' => 'Stadt',
    'zip_code' => 'Postleitzahl',
    'state_region_provice' => 'Bundesland / Region / Provinz',
    'region' => 'Region',
    'save_all' => 'Alle speichern',
    'info' => 'Info',
    'unpaid_warn' => 'Sie haben <span class="font-medium">:count</span> unbezahlte Rechnung(en). Bezahlen Sie sie rechtzeitig, um Unterbrechungen Ihres/des Dienstes/Dienste zu vermeiden.',
    'services' => 'Dienste',
    'invoices' => 'Rechnungen',
    'balance' => 'Kontostand',
    'change_color' => 'Farbe ändern',
    'customize_your_preference' => 'Passen Sie Ihre Einstellungen an Ihre Vorlieben an',
    'rose' => 'Rose',
    'pink' => 'Pink',
    'fuchsia' => 'Fuchsia',
    'purple' => 'Lila',
    'violet' => 'Violett',
    'indigo' => 'Indigo',
    'blue' => 'Blau',
    'sky' => 'Himmel',
    'cyan' => 'Cyan',
    'teal' => 'Blaugrün',
    'emerald' => 'Smaragd',
    'green' => 'Grün',
    'lime' => 'Limette',
    'yellow' => 'Gelb',
    'amber' => 'Bernstein',
    'orange' => 'Orange',
    'red' => 'Rot',
    'stone' => 'Stein',
    'neutral' => 'Neutral',
    'zinc' => 'Zink',
    'gray' => 'Grau',
    'slate' => 'Schiefer',
    'login' => 'Anmelden',
    'view_notifications' => 'Benachrichtigungen anzeigen',
    'notifications' => 'Benachrichtigungen',
    'icon_description' => 'Symbolbeschreibung',
    'mark_as_read' => 'Als gelesen markieren',
    'email_history' => 'E-Mail-Verlauf',
    'invoice_history' => 'Rechnungshistorie',
    'apps' => 'Apps',
    'open_user_menu' => 'Benutzermenü öffnen',
    'account_settings' => 'Kontoeinstellungen',
    'online' => 'Online',
    'away' => 'Abwesend',
    'busy' => 'Beschäftigt',
    'appear_offline' => 'Offline erscheinen',
    'subscriptions' => 'Abonnements',
    'admin' => 'Admin',
    'sign_out' => 'Abmelden',
    'last_login_at' => 'Letzte Anmeldung am',
    'never' => 'Nie',
    'member_since' => 'Mitglied seit',
    'visibility' => 'Sichtbarkeit',
    'update' => 'Aktualisieren',
    'dashboard' => 'Dashboard',
    'store' => 'Speichern',
    'view_all' => 'Alle anzeigen',
    'maintenance_mode_enabled' => 'Wartungsmodus aktiviert',
    'maintenance_mode_desc' => 'Dieses Panel ist aufgrund des aktivierten Wartungsmodus derzeit für Kunden nicht zugänglich. Sie umgehen derzeit den Wartungsmodus.',
    'disable_maintenance' => 'Wartungsmodus deaktivieren',
    'dismiss' => 'Verwerfen',
    'view_all_services' => 'Alle Dienste anzeigen',
    'close_menu' => 'Menü schließen',
    'balance_sidebar_desc' => 'Sobald die Zahlung abgeschlossen ist, wird der von Ihnen ausgewählte Betrag Ihrem Kontostand gutgeschrieben. Dadurch können Sie Ihre Dienste verlängern oder neue Bestellungen aufgeben.',
    'balance_how_add' => 'Wie viel möchten Sie hinzufügen?',
    'pay_now' => 'Jetzt bezahlen',
    'help_center' => 'Hilfe-Center',
    'resources' => 'Ressourcen',
    'legal' => 'Rechtlich',
    'all_rights_reserved' => 'Alle Rechte vorbehalten.',
    'price_block_desc' => 'Zuerst :period :symbol:total_price dann :symbol:renewal_price pro :per_period',
    'enter_domain' => 'Domain eingeben',
    'enter_domain_desc' => 'Bitte geben Sie die Domain ein, für die Sie diesen Dienst verwenden möchten.',
    'domain' => 'Domain',
    'enter_domain_helper' => 'Bitte geben Sie die genaue Domain ein, z.B. example.com oder wenn Sie eine Subdomain verwenden web.example.com',
    'payment_method' => 'Zahlungsmethode',
    'payment_method_desc' => 'Wählen Sie die gewünschte Zahlungsmethode aus',
    'subscription' => 'Abonnement',
    'custom_notes' => 'Benutzerdefinierte Notizen',
    'custom_notes_desc' => 'Sie können spezielle Anfragen oder Informationen, die wir wissen sollten, einschließen.',
    'custom_notes_placeholder' => 'Schreiben Sie Ihre Gedanken hier...',
    'order_summary' => 'Bestellübersicht',
    'recurring' => 'Wiederkehrend',
    'due_today' => 'Fällig heute',
    'complete_checkout' => 'Zur Kasse gehen',
    'selected_price_includes_cancellation_fee' => '*Der ausgewählte Preiszyklus beinhaltet eine Stornierungsgebühr von',
    'setup_fee' => 'Einrichtungsgebühr',
    'payment_canceled' => 'Zahlung abgebrochen',
    'payment_canceled_desc' => 'Ihre Zahlung wurde abgebrochen, bitte versuchen Sie es erneut.',
    'back_dashboard' => 'Zurück zum Dashboard',
    'view_invoice' => 'Rechnung anzeigen',
    'pricing' => 'Preise',
    'pricing_for' => 'Preise für',
    'get_started' => 'Loslegen',
    'payment_successfully' => 'Zahlung erfolgreich',
    'payment_successfully_desc' => 'Vielen Dank für die erfolgreiche Zahlung. Wir bereiten alles für Sie vor.',
    'create_subscription' => 'Abonnement erstellen',
    'subscription_name' => 'Abonnementname',
    'order' => 'Bestellen',
    'gateway' => 'Gateway',
    'billed_as' => 'Abgerechnet als',
    'next_billing_date' => 'Nächstes Abrechnungsdatum',
    'created_at' => 'Erstellt am',
    'active' => 'Aktiv',
    'days' => 'Tage',
    'manage' => 'Verwalten',
    'cancel' => 'Abbrechen',
    'close_modal' => 'Modal schließen',
    'subscription_order_desc' => 'Sie können ein Abonnement für vorhandene Bestellungen erstellen, um sie automatisch zu bezahlen, wenn es soweit ist.',
    'subscription_order' => 'Abonnement-Bestellung',
    'subscription_price' => 'Abonnement-Preis',
    'create' => 'Erstellen',
    'cancelling' => 'Abbrechen',
    'managing' => 'Verwalten',
    'close' => 'Schließen',
    'profile' => 'Profil',
    'client' => 'Kunde',
    'drag_and_drop' => '<span class="font-semibold">Klicken Sie hier zum Hochladen</span> oder ziehen Sie die Dateien per Drag & Drop',
    'upload' => 'Hochladen',
    'two_factor_authentication' => 'Zwei-Faktor-Authentifizierung',
    'two_factor_authentication_desc' => 'Die Zwei-Faktor-Authentifizierung fügt Ihrem Konto eine zusätzliche Sicherheitsebene hinzu, indem sie mehr als nur ein Passwort für die Anmeldung erfordert.',
    'social_accounts' => 'Social-Media-Konten',
    'google_account' => 'Google-Konto',
    'not_connected' => 'Nicht verbunden',
    'remove' => 'Entfernen',
    'connect' => 'Verbinden',
    'github_account' => 'GitHub-Konto',
    'discord_account' => 'Discord-Konto',
    'enable' => 'Aktivieren',
    'disable' => 'Deaktivieren',
    'download' => 'Herunterladen',
    'sessions' => 'Sitzungen',
    'last_seen' => 'Zuletzt gesehen',
    'revoked' => 'Entzogen',
    'revoke' => 'Entziehen',
    'general_information' => 'Allgemeine Informationen',
    'username' => 'Benutzername',
    'email' => 'E-Mail',
    'first_name' => 'Vorname',
    'subscribe_to_emails' => 'E-Mails abonnieren',
    'contact_us' => 'Kontaktieren Sie uns',
    'contact_us_desc' => 'Möchten Sie einen Fehler melden oder Hilfe bei der Suche nach dem richtigen Produkt erhalten? Wir werden uns bemühen, Ihnen so schnell wie möglich zu antworten.',
    'subject' => 'Betreff',
    'subject_contact_us_placeholder' => 'Lassen Sie uns wissen, wie wir Ihnen helfen können',
    'your_message' => 'Ihre Nachricht',
    'send_message' => 'Nachricht senden',
    'email_history_desc' => 'Durchsuchen Sie alle an Ihr Konto gesendeten E-Mails',
    'sender' => 'Absender',
    'address_only_vissible' => 'Adresse ist nur sichtbar für',
    'item' => 'Artikel',
    'price' => 'Preis',
    'qty' => 'Menge',
    'discounts' => 'Rabatte',
    'total' => 'Gesamt',
    'subtotal' => 'Zwischensumme',
    'tax_rate' => 'Steuersatz',
    'complete_payment' => 'Zahlung abschließen',
    'share' => 'Teilen',
    'sownload' => 'Herunterladen',
    'share_invoice_desc' => 'Sie können diese Rechnung mit einem anderen Benutzer teilen, damit er sie mit seinem Zahlungsgateway bezahlen kann. Ihre Adressdetails oder Ihr vollständiger Name werden nicht auf der Rechnung angezeigt.',
    'last_updated' => 'Zuletzt aktualisiert',
    'hello' => 'Hallo',
    'email_template_content' => 'Wenn Sie weitere Fragen haben oder fortlaufenden Support benötigen, können Sie uns über unser Online-Portal kontaktieren. Unser engagiertes Team steht Ihnen über das Ticketing-System schnell und effizient zur Verfügung.',
    'regards' => 'Mit freundlichen Grüßen',
    'email_button_desc' => 'Wenn Sie Probleme beim Klicken auf die Schaltfläche ":button" haben, kopieren Sie die folgende URL und fügen Sie sie in Ihren Webbrowser ein:',
    'open_main_menu' => 'Hauptmenü öffnen',
    'home' => 'Startseite',
    'features' => 'Funktionen',
    'contact' => 'Kontakt',
    'portal_redirect' => 'Portalumleitung',
    'portal_redirect_url' => 'Portal-Umleitungs-URL',
    'portal_header_image' => 'Portal-Headerbild',
    'default_category' => 'Standardkategorie',
    'submit' => 'Senden',
    'host_favorite_games' => 'Wir hosten Ihre Lieblingsspiele',
    'rust' => 'Rust',
    'minecraft' => 'Minecraft',
    'ack' => 'ARK: SE',
    'our_game_anel' => 'Unser Spielepanel',
    'our_game_anel_desc' => 'Hier bei :app konzentrieren wir uns auf Märkte, in denen Technologie, Innovation und Kapital langfristigen Wert schaffen und wirtschaftliches Wachstum fördern können.',
    'file_manager' => 'Dateimanager',
    'file_manager_desc' => 'Unser Dateimanager ermöglicht das Hochladen, Erstellen, Herunterladen, Festlegen von Berechtigungen, Zippen & Entpacken von Dateien und deren einfache Verwaltung',
    'plugins_manager' => 'Plugin-Manager',
    'plugins_manager_desc' => 'Wählen Sie aus über 60000 Plugins aus und installieren Sie sie mit nur einem Klick',
    'backup_manager' => 'Backup-Manager',
    'backup_manager_desc' => 'Unser Dashboard ermöglicht es Ihnen, zu einem beliebigen Zeitpunkt Backups Ihrer Dateien zu erstellen',
    'user_manager' => 'Benutzerverwaltung',
    'user_manager_desc' => 'Laden Sie Freunde oder Mitarbeiter in Ihr Dashboard ein. Sie können bestimmte Berechtigungen pro Mitglied festlegen',
    'schedule_manager' => 'Zeitplan-Manager',
    'schedule_manager_desc' => 'Unser Zeitplansystem ermöglicht es Ihnen, zeitgesteuerte Leistungssteuerungen, Backups oder Aufgaben festzulegen',
    'database_manager' => 'Datenbank-Manager',
    'database_manager_desc' => 'Generieren Sie MySQL-Datenbanken, erstellen Sie neue Allokationen und vieles mehr',
    'viewing_plans_for' => 'Anzeigen von Plänen für',
    'no_plans_display' => 'Keine Pläne anzeigen',
    'no_plans_display_desc' => 'Sie haben keine Pläne erstellt, die auf dem Portal angezeigt werden sollen. Erstellen Sie Pläne, um loszulegen.',
    'other_categories' => 'Andere Kategorien',
    'selected' => 'Ausgewählt',
    'get_started_now' => 'Jetzt loslegen',
    'register_your_account_no-time' => 'Registrieren Sie Ihr Konto und bringen Sie Ihren Server in kürzester Zeit zum Laufen!',
    'create_my_account' => 'Mein Konto erstellen',
    'try_again' => 'Erneut versuchen',
    'please_login_to_view' => 'Bitte melden Sie sich an, um diese Seite anzuzeigen.',
    'page_not_published' => 'Die Seite wurde noch nicht veröffentlicht.',
    'email_new_device_subject' => 'Ein neues Gerät hat sich bei Ihrem :app_name-Konto angemeldet',
    'email_check_activity_btn' => 'Aktivität überprüfen',
    'email_add_device_content' => '
                <br><br>
                Gerätedetails: <br>
                &bull; Gerät: :device_name <br>
                &bull; Gerätetyp: :device_type <br>
                &bull; IP-Adresse: :ip_address <br>
                &bull; Letzte Anmeldung: :last_login_at <br>
                &bull; Benutzer-Agent: <code>:user_agent</code> <br><br>

                Wenn Sie das nicht waren, widerrufen Sie sofort den Zugriff auf dieses Gerät und kontaktieren Sie uns.',
    'manage_service' => 'Dienst verwalten',
    'email_cancel_order_subject' => 'Ihr Dienst wurde storniert',
    'email_cancel_order_content' => '
            <br><br>
            Dienstdetails: <br>
            &bull; ID: #:id <br>
            &bull; Dienstname: :name <br>
            &bull; Gnadenfrist bis: :period <br>
            &bull; Stornierungsgrund: <code>:reason</code> <br><br>',
    'email_payment_completed_subject' => 'Zahlung erfolgreich',
    'email_payment_completed_button' => 'Rechnung anzeigen',
    'email_payment_completed_content' => '                <br><br>
                Zahlungsdetails: <br>
                &bull; Transaktions-ID: :id <br>
                &bull; Zahlungsbeschreibung: :description <br>
                &bull; Zahlungsbetrag: :amount_rounded :currency <br>
                &bull; Zahlungsmethode: :gateway_name <br><br>

                Ihre Zahlung wurde auf Ihr Konto angewendet, und alle relevanten Rechnungen oder ausstehenden Salden wurden entsprechend aktualisiert. <br>',
    'email_payment_refunded_subject' => 'Rückerstattung wird bearbeitet',
    'email_payment_refunded_content' => '                <br><br>
                Rückerstattungsdetails: <br>
                &bull; Transaktions-ID: :id <br>
                &bull; Zahlungsbeschreibung: :description <br>
                &bull; Rückerstattungsbetrag: :amount_rounded :currency <br>
                &bull; Rückerstattet an: :gateway_name <br><br>',
    'general' => 'Allgemein',
    'renew' => 'Verlängern',
    'ptero_alerts_suspended' => 'Dieser Dienst wurde gesperrt',
    'ptero_alerts_suspended_desc' => 'Das Fälligkeitsdatum für diesen Dienst war am :due_date (:due_date_diff)<br><br> Wir bedauern Ihnen mitteilen zu müssen, dass Ihr Dienst aufgrund ausstehender Zahlungen gesperrt wurde. Um eine Kündigung zu vermeiden, begleichen Sie bitte alle offenen Rechnungen innerhalb von :suspended_after Tagen nach dem Fälligkeitsdatum. Wenn die Zahlung innerhalb dieses Zeitraums nicht eingegangen ist, wird Ihr Dienst gekündigt, was zur Löschung oder Aufhebung aller damit verbundenen Daten, Dateien und Lizenzen führt.',
    'important' => 'Wichtig',
    'ptero_alerts_cancelled' => 'Dieser Dienst wurde storniert',
    'ptero_alerts_cancelled_desc' => 'Dieser Dienst soll am :cancelled_at (:cancelled_at_diff) storniert werden<br><br> Wenn Sie Ihre Meinung geändert haben, können Sie die Stornierung vor diesem Datum rückgängig machen. Wenn keine Maßnahmen ergriffen werden, wird Ihr Dienst gesperrt und gekündigt. Alle Dateien und Daten, die zu diesem Dienst gehören, werden endgültig gelöscht.',
    'do_not_cancel' => ' Nicht stornieren',
    'ptero_alerts_terminated' => 'Dieser Dienst wurde beendet',
    'ptero_alerts_terminated_desc' => 'Dieser Dienst wurde beendet. Eine Beendigung kann aus verschiedenen Gründen erfolgen. Sie waren mit der Zahlung zu spät oder haben den Dienst storniert. Alle zu diesem Dienst gehörenden Daten / Dateien / Lizenzen wurden gelöscht oder widerrufen. Dieser Vorgang ist nicht rückgängig zu machen.',
    'ptero_alerts_failed_server' => 'Fehler beim Erstellen Ihres Servers',
    'ptero_alerts_failed_server_desc' => 'Wir haben versucht, einen Server für Sie zu erstellen, jedoch ist etwas schiefgelaufen. Bitte kontaktieren Sie einen Administrator, um die Bestellung im Admin-Bereich für detailliertere Protokolle zu überprüfen.',
    'login_to_panel' => 'Im Panel anmelden',
    'cancel_plan' => 'Plan stornieren',
    'ptero_cancellation_fee_info' => '<span class="font-semibold">Wichtig!</span> In Ihrem Paket ist eine Stornierungsgebühr von :symbol:cancellation_fee enthalten, die zur Stornierung bezahlt werden muss',
    'cancel_at_end_of_term' => 'Am Ende der Laufzeit kündigen',
    'service_cancelled_gracefully_at_due_date' => 'Ihr Dienst wird zum Fälligkeitsdatum :due_date ordnungsgemäß gekündigt',
    'cancel_immediately' => 'Sofort stornieren',
    'cancel_immediately_desc' => 'Ihr Dienst wird innerhalb von 24 Stunden storniert. <br>Alle Dateien und Daten, die mit Ihrem Dienst verbunden sind, werden sofort gelöscht.</p>',
    'cancellation_reason' => 'Grund der Stornierung',
    'payment_method_reason' => 'Grund der Zahlungsmethode',
    'pay_with_balance' => 'Mit Guthaben bezahlen',
    'discard' => 'Verwerfen',
    'cancel_now' => 'Jetzt stornieren',
    'ptero_server_options' => 'Serveroptionen',
    'ptero_server_options_desc' => 'Bitte wählen Sie unten Ihre gewünschten Optionen aus.',
    'ptero_server_location' => 'Serverstandort',
    'ptero_renew_plan' => 'Plan verlängern',
    'create_invoice' => 'Rechnung erstellen',
    'renew_for' => 'Verlängern für',
    'ptero_renew_desc' => 'Ihr Dienst läuft am :due_date ab, :due_date_diff.<br><br>Nach dem Klicken auf "Verlängern" generieren wir eine Rechnung für Sie zum Bezahlen.',
    'create_location' => 'Standort erstellen',
    ];
